### PR TITLE
Remove warning for integer precision loss when building on 64-bit

### PR DESCRIPTION
**Pull request by guykogus**
… architecture.

### CODE REVIEW

**Comment by zenspider** [comment]
Where are you seeing warnings? I don't get any before your patch... (I'll still apply, just curious)

**Comment by guykogus** [comment]
We're using [CocoaPods-Keys](https://github.com/orta/cocoapods-keys) for an iOS project I'm working on, which is using this project for storing values in the Keychain. When that plug-in is installed for the first time those warnings come up, so I see them every time our continuous integration tasks run.

Also, I'm running macOS Sierra 10.12.3 and when I execute `ruby lib/osx_keychain.rb` I see those warnings as well, which was how I tested the fix.

**Comment by guykogus** [comment]
@zenspider will this be merged in?

**Comment by loudmouth** [comment]
I've also been seeing the same warnings and was curious if they may be causing issues I'm having with my CI as well. I'm all for being warning free and would love to see this merged.

**Comment by zenspider** [comment]
Can you please change it to match the actual type?

```
10061 % grep strlen /usr/include/string.h 
size_t	 strlen(const char *__s);
```

**Comment by guykogus** [comment]
I'm trying to convert it _away_ from that type, no? I'm trying to match the types used by the Security functions.

**Comment by zenspider** [comment]
Done. Thanks. Sorry I dragged my feet for so long.

**Pull request closed without merging**
